import type { Metadata } from "next";
import { Inter, Crimson_Text } from "next/font/google";
import "../globals.css";
import "remixicon/fonts/remixicon.css";
import { SanityLive } from "@/sanity/lib/live";
import { Toaster } from "sonner";
import { VisualEditing } from "next-sanity/visual-editing";
import { draftMode } from "next/headers";
import { DisableDraftMode } from "@/components/DisableDraftMode";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const crimson = Crimson_Text({
  weight: ["400", "600", "700"],
  variable: "--font-crimson",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body
        className={`${inter.variable} ${crimson.variable} font-inter antialiased`}
      >
        {children}

        <Toaster theme="dark" />

        {/* Live content API */}
        <SanityLive />

        {(await draftMode()).isEnabled && (
          <>
            <VisualEditing />
            <DisableDraftMode />
          </>
        )}
      </body>
    </html>
  );
}
