/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type RedesSociales = {
  _id: string;
  _type: "redesSociales";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  redes?: Array<{
    name?: "facebook" | "twitter" | "instagram" | "youtube" | "whatsapp" | "tiktok";
    title?: string;
    url?: string;
    _type: "redSocial";
    _key: string;
  }>;
};

export type PreguntasFrecuentes = {
  _id: string;
  _type: "preguntasFrecuentes";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  questions?: Array<{
    question?: string;
    answer?: string;
    _key: string;
  }>;
};

export type Blog = {
  _id: string;
  _type: "blog";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  description?: string;
  coverImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  genre?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "generoMusical";
  };
  content?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type GeneroMusical = {
  _id: string;
  _type: "generoMusical";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Contacto = {
  _id: string;
  _type: "contacto";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  description?: string;
  googleMapsCordenates?: string;
};

export type Testimonios = {
  _id: string;
  _type: "testimonios";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  description?: string;
  textTestimonials?: Array<{
    _key: string;
  } & TestimonioTexto>;
  videoTestimonials?: Array<{
    _key: string;
  } & TestimonioVideo>;
};

export type TestimonioVideo = {
  _type: "testimonioVideo";
  video?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
    };
    media?: unknown;
    _type: "file";
  };
};

export type TestimonioTexto = {
  _type: "testimonioTexto";
  reference?: string;
  name?: string;
};

export type SobreNosotros = {
  _id: string;
  _type: "sobreNosotros";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  subtitle?: string;
  description?: string;
  buttonDescription?: string;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type Performance = {
  _id: string;
  _type: "performance";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  description?: string;
  images?: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
};

export type Servicios = {
  _id: string;
  _type: "servicios";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  description?: string;
  services?: Array<{
    title?: string;
    description?: string;
    icon?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    _key: string;
  }>;
};

export type Eventos = {
  _id: string;
  _type: "eventos";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  description?: string;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  eventList?: Array<{
    _key: string;
  } & Evento>;
};

export type Evento = {
  _type: "evento";
  title?: string;
  description?: string;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  date?: string;
  url?: string;
};

export type Hero = {
  _id: string;
  _type: "hero";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  backgroundImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  announcement?: string;
  title?: string;
  subtitle?: string;
  darkenImage?: boolean;
  blurText?: boolean;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes = RedesSociales | PreguntasFrecuentes | Blog | GeneroMusical | Slug | SanityImageCrop | SanityImageHotspot | Contacto | Testimonios | TestimonioVideo | TestimonioTexto | SobreNosotros | Performance | Servicios | Eventos | Evento | Hero | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageMetadata | SanityFileAsset | SanityAssetSourceData | SanityImageAsset | Geopoint;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ./app/(routes)/blog/[id]/page.tsx
// Variable: BLOG_QUERY
// Query: *[_type == "blog" && _id == $id][0]{  _id,  title,  description,  coverImage,  genre->{    name,    slug  },  content}
export type BLOG_QUERYResult = {
  _id: string;
  title: string | null;
  description: string | null;
  coverImage: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  genre: {
    name: string | null;
    slug: Slug | null;
  } | null;
  content: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
} | null;

// Source: ./app/(routes)/blog/page.tsx
// Variable: BLOGS_QUERY
// Query: *[_type == "blog"] | order(_createdAt desc){  _id,  title,  description,  coverImage,  genre->{    name,    slug  },  _createdAt}
export type BLOGS_QUERYResult = Array<{
  _id: string;
  title: string | null;
  description: string | null;
  coverImage: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  genre: {
    name: string | null;
    slug: Slug | null;
  } | null;
  _createdAt: string;
}>;

// Source: ./sanity/query/Eventos.ts
// Variable: EVENTOS_QUERY
// Query: *[_id == "eventos"][0]{  _id,  title,  description,  image,  eventList[]{    title,    description,    image,    date,    url  }}
export type EVENTOS_QUERYResult = {
  _id: string;
  title: null;
  description: null;
  image: null;
  eventList: null;
} | {
  _id: string;
  title: string | null;
  description: null;
  image: null;
  eventList: null;
} | {
  _id: string;
  title: string | null;
  description: string | null;
  image: null;
  eventList: null;
} | {
  _id: string;
  title: string | null;
  description: string | null;
  image: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  eventList: null;
} | {
  _id: string;
  title: string | null;
  description: string | null;
  image: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  eventList: Array<{
    title: string | null;
    description: string | null;
    image: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    date: string | null;
    url: string | null;
  }> | null;
} | null;

// Source: ./sanity/query/Generos.ts
// Variable: GENEROS_QUERY
// Query: *[_type == "generoMusical"]{  _id,  name,  slug}
export type GENEROS_QUERYResult = Array<{
  _id: string;
  name: string | null;
  slug: Slug | null;
}>;

// Source: ./sanity/query/HomeQuery.ts
// Variable: HERO_QUERY
// Query: *[_id == "hero"][0]{  backgroundImage,  darkenImage,  blurText,  announcement,  title,  subtitle  }
export type HERO_QUERYResult = {
  backgroundImage: null;
  darkenImage: null;
  blurText: null;
  announcement: null;
  title: null;
  subtitle: null;
} | {
  backgroundImage: null;
  darkenImage: null;
  blurText: null;
  announcement: null;
  title: string | null;
  subtitle: null;
} | {
  backgroundImage: null;
  darkenImage: null;
  blurText: null;
  announcement: null;
  title: string | null;
  subtitle: string | null;
} | {
  backgroundImage: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  darkenImage: boolean | null;
  blurText: boolean | null;
  announcement: string | null;
  title: string | null;
  subtitle: string | null;
} | null;
// Variable: SERVICIOS_QUERY
// Query: *[_id == "servicios"][0]{  title,  description,  services,  }
export type SERVICIOS_QUERYResult = {
  title: null;
  description: null;
  services: null;
} | {
  title: string | null;
  description: null;
  services: null;
} | {
  title: string | null;
  description: string | null;
  services: null;
} | {
  title: string | null;
  description: string | null;
  services: Array<{
    title?: string;
    description?: string;
    icon?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    _key: string;
  }> | null;
} | null;
// Variable: PERFORMANCE_QUERY
// Query: *[_type == "performance"][0]{  title,  description,  images[]{    asset->{      _id,      url,      metadata {        dimensions {          width,          height,          aspectRatio        }      }    }  }}
export type PERFORMANCE_QUERYResult = {
  title: string | null;
  description: string | null;
  images: Array<{
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        dimensions: {
          width: number | null;
          height: number | null;
          aspectRatio: number | null;
        } | null;
      } | null;
    } | null;
  }> | null;
} | null;
// Variable: TESTIMONIOS_QUERY
// Query: *[_type == "testimonios"][0]{  _id,  title,  description,  textTestimonials[]{    reference,    name  },  videoTestimonials[]{    video{      asset->{        _id,        url      }    }  }}
export type TESTIMONIOS_QUERYResult = {
  _id: string;
  title: string | null;
  description: string | null;
  textTestimonials: Array<{
    reference: string | null;
    name: string | null;
  }> | null;
  videoTestimonials: Array<{
    video: {
      asset: {
        _id: string;
        url: string | null;
      } | null;
    } | null;
  }> | null;
} | null;
// Variable: PREGUNTAS_QUERY
// Query: *[_type == "preguntasFrecuentes"][0]{  _id,  title,  questions[]{    question,    answer  }}
export type PREGUNTAS_QUERYResult = {
  _id: string;
  title: string | null;
  questions: Array<{
    question: string | null;
    answer: string | null;
  }> | null;
} | null;
// Variable: NOSOTROS_QUERY
// Query: *[_id == "sobreNosotros"][0]{  title,  subtitle,  description,  buttonDescription,  image,  }
export type NOSOTROS_QUERYResult = {
  title: null;
  subtitle: null;
  description: null;
  buttonDescription: null;
  image: null;
} | {
  title: string | null;
  subtitle: null;
  description: null;
  buttonDescription: null;
  image: null;
} | {
  title: string | null;
  subtitle: string | null;
  description: null;
  buttonDescription: null;
  image: null;
} | {
  title: string | null;
  subtitle: null;
  description: string | null;
  buttonDescription: null;
  image: null;
} | {
  title: string | null;
  subtitle: null;
  description: string | null;
  buttonDescription: null;
  image: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
} | {
  title: string | null;
  subtitle: string | null;
  description: string | null;
  buttonDescription: string | null;
  image: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
} | null;
// Variable: CONTACTO_QUERY
// Query: *[_type == "contacto"][0]{  _id,  title,  description,  googleMapsCordenates}
export type CONTACTO_QUERYResult = {
  _id: string;
  title: string | null;
  description: string | null;
  googleMapsCordenates: string | null;
} | null;

// Source: ./sanity/query/RedesSociales.ts
// Variable: REDES_QUERY
// Query: *[_type == "redesSociales"][0]{  redes}
export type REDES_QUERYResult = {
  redes: Array<{
    name?: "facebook" | "instagram" | "tiktok" | "twitter" | "whatsapp" | "youtube";
    title?: string;
    url?: string;
    _type: "redSocial";
    _key: string;
  }> | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "*[_type == \"blog\" && _id == $id][0]{\n  _id,\n  title,\n  description,\n  coverImage,\n  genre->{\n    name,\n    slug\n  },\n  content\n}": BLOG_QUERYResult;
    "*[_type == \"blog\"] | order(_createdAt desc){\n  _id,\n  title,\n  description,\n  coverImage,\n  genre->{\n    name,\n    slug\n  },\n  _createdAt\n}": BLOGS_QUERYResult;
    "*[_id == \"eventos\"][0]{\n  _id,\n  title,\n  description,\n  image,\n  eventList[]{\n    title,\n    description,\n    image,\n    date,\n    url\n  }\n}": EVENTOS_QUERYResult;
    "*[_type == \"generoMusical\"]{\n  _id,\n  name,\n  slug\n}": GENEROS_QUERYResult;
    "*[_id == \"hero\"][0]{\n  backgroundImage,\n  darkenImage,\n  blurText,\n  announcement,\n  title,\n  subtitle\n  }": HERO_QUERYResult;
    "*[_id == \"servicios\"][0]{\n  title,\n  description,\n  services,\n  }": SERVICIOS_QUERYResult;
    "*[_type == \"performance\"][0]{\n  title,\n  description,\n  images[]{\n    asset->{\n      _id,\n      url,\n      metadata {\n        dimensions {\n          width,\n          height,\n          aspectRatio\n        }\n      }\n    }\n  }\n}": PERFORMANCE_QUERYResult;
    "*[_type == \"testimonios\"][0]{\n  _id,\n  title,\n  description,\n  textTestimonials[]{\n    reference,\n    name\n  },\n  videoTestimonials[]{\n    video{\n      asset->{\n        _id,\n        url\n      }\n    }\n  }\n}": TESTIMONIOS_QUERYResult;
    "*[_type == \"preguntasFrecuentes\"][0]{\n  _id,\n  title,\n  questions[]{\n    question,\n    answer\n  }\n}": PREGUNTAS_QUERYResult;
    "*[_id == \"sobreNosotros\"][0]{\n  title,\n  subtitle,\n  description,\n  buttonDescription,\n  image,\n  }": NOSOTROS_QUERYResult;
    "*[_type == \"contacto\"][0]{\n  _id,\n  title,\n  description,\n  googleMapsCordenates\n}": CONTACTO_QUERYResult;
    "*[_type == \"redesSociales\"][0]{\n  redes\n}": REDES_QUERYResult;
  }
}
